---
# tasks file for roles/Pre_checks
  - name: check interfaces 
    ios_command:
        commands:
           - "{{ item }}"
    loop:
           - show ip int brief
           - show ip route
    register: out_t


  - name: debug checks info
    debug:
      msg:
        - "{{ item.invocation.module_args.commands }}" 
        - "{{ item.stdout_lines }}"
    loop: "{{  out_t.results}}"
    loop_control:
         label: In