---
# tasks file for roles/Sii_Rollback
- name: generat config rollback
  template:
     src: templates/delete_interface.j2
     dest: files/{{ inventory_hostname}}_delete_config
 

- name: push conf
  ios_config:
      src: files/{{ inventory_hostname}}_delete_config
  become: yes
  tags:
    - push